name: Static Variable Check

on:
  pull_request:
    branches:
      - master

jobs:
  detect-static-vars:
    name: Detect Static Variables in Java Code
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Search for static variables with inline whitelist
        run: |
          echo "🔍 Scanning for unapproved static variable usage..."
          ALL_STATIC=$(grep -Prn --include="*.java" '\bstatic\s+(?!final\b)[\w<>\[\]]+\s+\w+\s*(=|;)' .)

          # Allow inline whitelisted lines
          UNAPPROVED=$(echo "$ALL_STATIC" | grep -v '// static-ok' || true)

          if [ -n "$UNAPPROVED" ]; then
            echo "⚠️ WARNING: Unapproved static variables detected:"
            echo "$UNAPPROVED"
          else
            echo "✅ All static variables are explicitly approved."
          fi
