name: Static Variable Check

on:
  pull_request:
    branches:
      - master

jobs:
  detect-static-vars:
    name: Detect Static Variables in Java Code
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Search for static variables
        run: |
          echo "🚨 Scanning for static variables..."

          STATIC_VARS=$(grep -Prn --include="*.java" --exclude-dir={.git,test} '\bstatic\s+(?!final\b)[\w<>\[\]]+\s+\w+\s*(=|;)' .)

          if [ -n "$STATIC_VARS" ]; then
            echo "❌ Static variables found:"
            echo "$STATIC_VARS"
            exit 1
          else
            echo "✅ No static variables found."
          fi
