name: Static Variable Check

on:
  pull_request:
    branches:
      - master

jobs:
  detect-static-vars:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          fetch-depth: 0  # Required to diff against base branch

      - name: Detect static variables in changed files
        run: |
          echo "🔍 Scanning for static variables in changed Java files..."

          # Get list of changed .java files in the PR
          FILES=$(git diff --name-only origin/${{ github.base_ref }}...${{ github.sha }} | grep '\.java$' || true)

          if [[ -z "$FILES" ]]; then
            echo "✅ No Java files changed. Skipping static var check."
            exit 0
          fi

          echo "📁 Files to check:"
          echo "$FILES"

          EXIT_CODE=0

          for file in $FILES; do
            echo "📄 Checking $file"
            STATIC_LINES=$(grep -nP '\bstatic\s+(?!final\b)[\w<>\[\]]+\s+\w+\s*(=|;)' "$file" | grep -v '// static-ok' || true)

            if [[ -n "$STATIC_LINES" ]]; then
              echo "❌ Unapproved static variables in $file:"
              echo "$STATIC_LINES"
              EXIT_CODE=1
            fi
          done

          if [[ "$EXIT_CODE" -eq 0 ]]; then
            echo "✅ No unapproved static variables found."
          fi

          exit $EXIT_CODE
