name: Static Variable Check with Manual Approval

on:
  pull_request:
    types: [opened, synchronize, reopened, edited]

jobs:
  check-static-vars:
    runs-on: ubuntu-latest
    permissions:
      pull-requests: read

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Detect static variables
        id: scan
        run: |
          echo "🔍 Scanning for static variables..."
          STATIC_VARS=$(grep -Prn --include="*.java" '\bstatic\s+(?!final\b)[\w<>\[\]]+\s+\w+\s*(=|;)' . || true)

          echo "static_found<<EOF" >> $GITHUB_OUTPUT
          echo "$STATIC_VARS" >> $GITHUB_OUTPUT
          echo "EOF" >> $GITHUB_OUTPUT

      - name: Check for approval comment
        id: check_comment
        uses: peter-evans/find-comment@v3
        with:
          issue-number: ${{ github.event.pull_request.number }}
          body-includes: "/approve static use"

      - name: Evaluate static variable policy
        run: |
          echo "🧪 Evaluating static variable findings..."

          if [[ "${{ steps.scan.outputs.static_found }}" != "" ]] && [[ "${{ steps.check_comment.outputs.comment-id }}" == "" ]]; then
            echo "❌ Static variables found and no approval given."
            echo "${{ steps.scan.outputs.static_found }}"
            exit 1
          else
            echo "✅ Either no statics found or approval exists."
          fi
